package com.khh._cxf.demo2.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-17T20:56:13.852+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://server.demo2._cxf.khh.com/", name = "WeatherInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterface {

    @WebMethod
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://server.demo2._cxf.khh.com/", className = "com.khh._cxf.demo2.client.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://server.demo2._cxf.khh.com/", className = "com.khh._cxf.demo2.client.QueryWeatherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String queryWeather(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
